# Wire up travis
language: python
sudo: false

env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=coverage

install:
  - travis_retry pip install tox

script:
  - travis_retry tox

notifications:
  email:
    - repoze-checkins@lists.repoze.org
